name: "Calibre Web UI"
description: "A lightweight web interface for the Calibre CLI, allowing book management, conversion, and Kindle LAN access."
version: "1.1.1"
slug: "calibre_web_ui"
ingress: true
ingress_port: 8080
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
map:
  - share:rw
options:
  library_path: "/share/calibre"
  log_level: "info"
schema:
  library_path: "str"
  log_level: "list(debug|info|warning|error)"
ports:
  8080/tcp: 8080
